---
- hosts: webserver
  become: true
  remote_user: ec2-user
  roles:
    - roles     
  tasks:
    - iptables:
         flush: yes
         comment: flush all other rules
    - iptables:
         chain: INPUT
         protocol: tcp
         match: tcp
         source: 223.181.127.87 
         destination_port: 80
         jump: ACCEPT
    - iptables:
         chain: INPUT
         protocol: tcp
         match: tcp
         source: 223.181.127.87
         destination_port: 22
         jump: ACCEPT
    - iptables:
         chain: OUTPUT
         protocol: tcp
         match: tcp
         destination_port: 22
         jump: ACCEPT
    - iptables:
         chain: FORWARD
         policy: DROP


